version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config/jellyfin:/config
      - ./media/movies:/data/movies
      - ./media/tv:/data/tv
    ports:
      - 8096:8096
    restart: unless-stopped
